// Define a koa server to host the universal web app

import path from 'path';
import koa from 'koa';
import serveStatic from 'koa-static';
import favicon from 'koa-favi';
import jade from 'koa-jade';
import React from 'react';

import resolveAssetPath from './resolveAssetPath';
import HelloWorld from '../app/components/HelloWorld';

export default (config, callback) => {
  global.__CLIENT__ = false;
  global.__SERVER__ = true;
  global.__DEV__    = config.env !== 'production';

  const app = koa();

  // use default node favicon
  app.use(favicon());

  // serve static assets generated by the build process
  app.use(serveStatic(path.resolve(__dirname, '../dist')));

  // replace jade vars here
  const locals = {
    jsAssets: resolveAssetPath('app','js'),
    body: React.renderToString(
      <HelloWorld location="server" />
    )
  };

  // register jade middleware
  app.use(jade.middleware({
    viewPath: __dirname + '/views',
    debug: false,
    pretty: false,
    compileDebug: false,
    noCache: true
  }));

  app.use(function *() {
    this.render('index', locals)
  });

  return app.listen(config.port, () => callback(config, app));
}
